from sqlalchemy import Column, String, Integer, Text, ForeignKey, DateTime, func
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()

class AccidentMeta(Base):
    __tablename__ = "A_FILE"

    report_id = Column("c5", String, primary_key=True, index=True, comment="Unique control number used to relate to AID_MAIN table. (AID_MAIN 테이블과 관련된 고유 제어 번호.)")
    event_type = Column("c1", String, comment="Type of Event (이벤트 유형)")
    far_part_number = Column("c2", String, comment="FAR part number (FAR 부품 번호)")
    latest_data_source = Column("c3", String, comment="Form on which the latest data was received. (최신 데이터가 수신된 양식.)")
    investigation_agency = Column("c4", String, comment="Agency conducting investigation. (조사를 진행하는 기관.)")
    year = Column("c6", String, comment="Year the accident/incident happened. (사고/사고가 발생한 해.)")
    month = Column("c7", String, comment="Month the accident/incident happened. (사고/사고가 발생한 달.)")
    day = Column("c8", String, comment="Day the accident/incident happened. (사고/사고가 발생한 날.)")
    date = Column("c9", String, comment="Date the accident/incident happened. (사고/사고가 발생한 날짜.)")
    local_time = Column("c10", String, comment="Local time of the accident/incident. (사고/사고의 현지 시간.)")
    region = Column("c11", String, comment="Region of the accident/incident location. (사고/사고 위치의 지역.)")
    district_office = Column("c12", String, comment="District office of the accident/incident location. (사고/사고 위치의 구청.)")
    state = Column("c13", String, comment="State of the accident/incident location. (사고/사고 위치 상태.)")
    city = Column("c14", String, comment="City of the accident/incident location. (사고/사고 장소의 도시.)")
    airport_name = Column("c15", String, comment="Name of the airport (공항 이름)")
    runway_number = Column("c16", String, comment="Airport runway number (공항 활주로 번호)")
    nearest_airport_id = Column("c17", String, comment="Location identification code of the nearest airport, if not on airport. (공항 내가 아닌 경우 가장 가까운 공항의 위치 식별 코드.)")
    direction_from_airport = Column("c18", String, comment="Direction from the airport location identifier. (공항 위치 식별자에서 오는 방향.)")
    distance_from_airport = Column("c19", String, comment="Distance from the airport location identifier. (공항 위치 식별자로부터의 거리.)")
    latitude = Column("c20", String, comment="Latitude coordinates of the accident/incident (사고/사고의 위도 좌표)")
    longitude = Column("c21", String, comment="Longitude coordinates of the accident/incident (사고/사고의 경도 좌표)")
    aircraft_registration = Column("c22", String, comment="Aircraft Registration or N Number . (항공기 등록 또는 N 번호.)")
    aircraft_make = Column("c23", String, comment="Make of the aircraft (항공기 제작)")
    aircraft_model = Column("c24", String, comment="Model of the aircraft (항공기 모델)")
    aircraft_group = Column("c25", String, comment="Group of the aircraft (항공기 그룹)")
    aircraft_cert_data = Column("c26", String, comment="Technical certificate data sheet information of the aircraft (항공기의 기술 인증서 데이터 시트 정보)")
    aircraft_cert_region = Column("c27", String, comment="Region of certification for the aircraft (항공기 인증 지역)")
    airworthiness_class = Column("c30", String, comment="Airworthiness class code of the aircraft (항공기의 감항성 등급 코드)")
    airframe_hours = Column("c31", String, comment="Airframe hours of the aircraft (항공기의 기체 시간)")
    manufacture_year = Column("c32", String, comment="This field contains the year of manufacture of the aircraft (이 분야에는 항공기 제조 연도가 포함되어 있습니다)")
    wing_type = Column("c33", String, comment="Low wing, high wing, rotary wing, etc. (로우 윙, 하이 윙, 로터리 윙 등.)")
    engine_make = Column("c34", String, comment="Make of the engine (엔진 제작)")
    engine_model = Column("c35", String, comment="Model of the engine (엔진 모델)")
    engine_group = Column("c36", String, comment="Group of the engine (엔진 그룹)")
    engine_cert_data = Column("c37", String, comment="Technical certificate data sheet information of the engine (엔진의 기술 인증서 데이터 시트 정보)")
    engine_cert_region = Column("c38", String, comment="Certificating region of the engine (엔진 인증 영역)")
    engine_type = Column("c39", String, comment="Piston, turbine, turboprop, etc. (피스톤, 터빈, 터보프롭 등.)")
    pilot_cert_type_text = Column("c40", String, comment="Certificate type text of the pilot in command (명령 중인 조종사의 인증서 유형 텍스트)")
    pilot_cert_type_code = Column("c41", String, comment="Certificate type code of the pilot in command (명령 중인 조종사의 인증서 유형 코드)")
    not_used_c43 = Column("c43", String, comment="Not used at present time. (현재 사용되지 않습니다.)")
    pilot_rating_desc = Column("c44", String, comment="Rating description of the pilot in command (지휘 중인 조종사의 등급 설명)")
    pilot_rating_code = Column("c45", String, comment="Rating code of the pilot in command (조종사의 등급 코드)")
    pilot_other_rating_desc = Column("c46", String, comment="Any other rating description of the pilot in command (지휘 중인 조종사에 대한 기타 등급 설명)")
    pilot_other_rating_code = Column("c47", String, comment="Any other rating code of the pilot in command . (명령에 있는 조종사의 다른 등급 코드 .)")
    pilot_qual_desc = Column("c48", String, comment="Qualification description of the pilot in command (조종사의 자격 설명)")
    pilot_qual_code = Column("c49", String, comment="Qualification code of the pilot in command . (조종사 자격 코드 .)")
    pilot_age = Column("c50", String, comment="Age of the pilot in command (조종사의 연령)")
    pilot_profession_desc = Column("c51", String, comment="Profession description of the pilot in command (조종사의 직업 설명)")
    pilot_profession_code = Column("c52", String, comment="Profession code of the pilot in command (조종사의 직업 코드)")
    flight_hours_total_make_model = Column("c53", String, comment="Total number of hours the pilot has flown in the specific make and model of the aircraft . (조종사가 항공기의 특정 제작사와 모델을 비행한 총 시간 .)")
    flight_hours_90days_make_model = Column("c54", String, comment="Total number of hours in the last 90 days the pilot has flown this make and model (지난 90일 동안 조종사가 이 제조업체와 모델을 비행한 총 시간)")
    flight_hours_90days = Column("c55", String, comment="Total number of hours in the last 90 days the pilot has flown. (지난 90일 동안 조종사가 비행한 총 시간 수입니다.)")
    flight_hours_total = Column("c56", String, comment="Total number of hours the pilot has flown. (조종사가 비행한 총 시간 수입니다.)")
    pilot_residence_region = Column("c57", String, comment="Residence region code of the pilot in command (조종사의 거주 지역 코드)")
    pilot_residence_district = Column("c58", String, comment="Residence district office code of the pilot in command (지휘하는 조종사의 거주 지역 사무소 코드)")
    pilot_residence_state = Column("c59", String, comment="Residence state of the pilot in command (지휘하는 조종사의 거주 상태)")
    total_onboard = Column("c61", String, comment="Including crew and passengers. (승무원과 승객을 포함하여.)")
    passengers_onboard = Column("c62", String, comment="Number of passengers onboard (탑승 승객 수)")
    passengers_killed = Column("c63", String, comment="Number of passengers killed (사망한 승객 수)")
    passengers_injured = Column("c64", String, comment="Number of passengers injured (부상당한 승객 수)")
    crew_onboard = Column("c65", String, comment="Number of flight crew members onboard (탑승한 승무원 수)")
    crew_killed = Column("c66", String, comment="Number of flight crew members killed (사망한 승무원 수)")
    crew_injured = Column("c67", String, comment="Number of flight crew members injured (승무원 부상자 수)")
    cabin_crew_onboard = Column("c68", String, comment="Number of cabin crew members onboard (탑승한 객실 승무원 수)")
    cabin_crew_injured = Column("c69", String, comment="Number of cabin crew members injured (승무원 부상자 수)")
    cabin_crew_killed = Column("c70", String, comment="Number of cabin crew members killed (사망한 객실 승무원 수)")
    ground_crew_injured = Column("c71", String, comment="Number of ground crew members injured (지상 승무원 부상자 수)")
    ground_crew_killed = Column("c72", String, comment="Number of ground crew members killed (지상 승무원 사망자 수)")
    public_injured = Column("c73", String, comment="Number of public/third party persons injured (공공/제3자 부상자 수)")
    public_killed = Column("c74", String, comment="Number of public/third party persons killed (공개/제3자 사망자 수)")
    midair_collision_indicator = Column("c75", String, comment="First, second, or third airplane involved or Not a midair. (첫 번째, 두 번째, 또는 세 번째 비행기가 공중에 있는지 여부.)")
    total_fatalities = Column("c76", String, comment="Total Fatalities (총 사망자 수)")
    primary_cause_text = Column("c77", String, comment="Primary cause factor text (주요 원인 요인 텍스트)")
    primary_cause_code = Column("c78", String, comment="Primary cause factor code (주요 원인 요인 코드)")
    contributing_factor_text = Column("c79", String, comment="Contributing factor text (기여 요인 텍스트)")
    contributing_factor_code = Column("c80", String, comment="Contributing factor code (기여 요인 코드)")
    persons_involved_text = Column("c81", String, comment="Persons involved text (관련된 사람들 텍스트)")
    persons_involved_code = Column("c82", String, comment="Persons involved code (관련자 코드)")
    support_factor_tech_text = Column("c83", String, comment="Supporting factor text TECHNICAL (보조 요소 텍스트 기술)")
    support_factor_tech_code = Column("c84", String, comment="Supporting factor code TECHNICAL (보조 요인 코드 기술)")
    second_cause_text = Column("c85", String, comment="Second cause factor text (두 번째 원인 요인 텍스트)")
    second_cause_code = Column("c86", String, comment="Secondary cause factor code (이차 원인 인자 코드)")
    second_contributing_text = Column("c87", String, comment="Second contributing factor text (두 번째 기여 요인 텍스트)")
    second_contributing_code = Column("c88", String, comment="Second contributing case code f (두 번째 기여 사례 코드 f)")
    second_person_involved_text = Column("c89", String, comment="Second persons involved text (관련된 2인칭 텍스트)")
    second_person_involved_code = Column("c90", String, comment="Second persons involved code (관련된 두 번째 사람 코드)")
    second_support_factor_tech_text = Column("c91", String, comment="Second supporting factor text TECHNICAL (두 번째 보조 요소 텍스트 기술)")
    second_support_factor_tech_code = Column("c92", String, comment="Second supporting factor code . TECHNICAL (두 번째 보조 요인 코드 . 기술)")
    accident_type_text = Column("c93", String, comment="Type of accident or incident text (사고 유형 또는 사건 텍스트)")
    accident_type_code = Column("c94", String, comment="Type of accident code (사고 코드 유형)")
    flight_phase_text = Column("c95", String, comment="Phase of flight text (비행 텍스트의 단계)")
    flight_phase_code = Column("c96", String, comment="Phase of flight code (비행 코드 단계)")
    damage_text = Column("c97", String, comment="Damage text (손상 텍스트)")
    damage_code = Column("c98", String, comment="Damage code of aircraft. (항공기의 손상 코드.)")
    general_cause_text = Column("c99", String, comment="General cause category text (일반 원인 카테고리 텍스트)")
    general_cause_code = Column("c100", String, comment="General cause category code (일반 원인 카테고리 코드)")
    primary_flight_type_text = Column("c101", String, comment="Primary type of flying text (기본 비행 텍스트 유형)")
    primary_flight_type_code = Column("c102", String, comment="Primary type of flying code (기본 비행 코드 유형)")
    secondary_flight_type_text = Column("c103", String, comment="Secondary type of flying text (부차적인 비행 텍스트 유형)")
    secondary_flight_type_code = Column("c104", String, comment="Secondary type of flying code (보조 비행 코드 유형)")
    primary_flight_cond_text = Column("c105", String, comment="Primary flying condition text (기본 비행 조건 텍스트)")
    primary_flight_cond_code = Column("c106", String, comment="Primary flying condition code (주 비행 조건 코드)")
    secondary_flight_cond_text = Column("c107", String, comment="Secondary flying condition text (이차 비행 조건 텍스트)")
    secondary_flight_cond_code = Column("c108", String, comment="Secondary flying condition code (이차 비행 조건 코드)")
    light_cond_text = Column("c109", String, comment="Light condition text (조명 조건 텍스트)")
    light_cond_code = Column("c110", String, comment="Light condition code (조명 조건 코드)")
    approach_type_code = Column("c111", String, comment="Type of approach code (접근 코드 유형)")
    sky_cond_code = Column("c112", String, comment="Sky condition code (하늘 조건 코드)")
    ceiling_height = Column("c113", String, comment="Cloud ceiling (구름 천장)")
    visibility_code = Column("c114", String, comment="Visibility code (가시성 코드)")
    visibility_restriction_code = Column("c115", String, comment="Visibility restriction code. (가시성 제한 코드.)")
    runway_cond_code = Column("c117", String, comment="Runway condition code (활주로 조건 코드)")
    braking_cond_code = Column("c118", String, comment="Braking condition code (제동 조건 코드)")
    remarks = Column("c119", String, comment="Partial remarks on reports and where space needs to be conserved. (보고서와 공간 보존이 필요한 부분에 대한 부분적인 언급.)")
    operator_name = Column("c120", String, comment="Name of the owner / operator of aircraft (항공기 소유자/운항자의 이름)")
    operator_state = Column("c121", String, comment="State of the owner / operator (소유자/운영자의 상태)")
    operator_code = Column("c122", String, comment="Designator code of the air operator (OPCD) (항공사 지정자 코드(OPCD))")
    elt_onboard = Column("c123", String, comment="Emergency Locator Transmitter on Board? Y or N (비상 로케이터 송신기 탑재? Y 또는 N)")
    c124_flag = Column("c124", String, comment="Y or N. (Y 또는 N.)")
    c125_flag = Column("c125", String, comment="Y or N. (Y 또는 N.)")
    agency_cert_number = Column("c126", String, comment="Certificate number of the air agency (항공사의 인증서 번호)")
    operator_region = Column("c127", String, comment="Region of the air operator (항공 운영자의 지역)")
    operator_district = Column("c128", String, comment="District office of the air operator (항공사 구청)")
    ntsb_file_number = Column("c129", String, comment="NTSB File number of the accident/incident. (NTSB 사고/사고 파일 번호.)")
    flight_plan_desc = Column("c130", String, comment="Flight plan description (비행 계획 설명)")
    remedial_action1_area_text = Column("c131", String, comment="First remedial action area text (첫 번째 교정 조치 영역 텍스트)")
    remedial_action1_area_code = Column("c132", String, comment="First remedial action area code (첫 번째 교정 조치 지역 코드)")
    remedial_action_taken_text = Column("c133", String, comment="Remedial action taken text (수정 조치 완료 텍스트)")
    remedial_action1_taken_code = Column("c134", String, comment="First remedial action taken code (첫 번째 교정 조치가 취해진 코드)")
    remedial_action2_area_text = Column("c135", String, comment="Second remedial action area text (두 번째 교정 조치 영역 텍스트)")
    remedial_action2_area_code = Column("c136", String, comment="Second remedial action area code (두 번째 교정 조치 지역 코드)")
    remedial_action2_taken_text = Column("c137", String, comment="Second remedial action taken text (두 번째 수정 조치가 취해졌습니다)")
    remedial_action2_taken_code = Column("c138", String, comment="Second remedial action taken code (두 번째 수정 조치가 취해졌습니다. 코드)")
    related_report_code = Column("c139", String, comment="Code for related reports pertaining to the accident/incident. (사고/사고와 관련된 관련 보고서의 코드.)")
    investigation_extent = Column("c140", String, comment="Extent of investigation (조사 범위)")
    notification_method = Column("c141", String, comment="Method of notification (통지 방법)")
    airport_id = Column("c143", String, comment="Airport identification code of the accident/incident location, if on airport. (공항에 있는 경우 사고/사고 위치의 공항 식별 코드.)")
    aircraft_design_code = Column("c144", String, comment="Code for Aircraft Design (항공기 설계 강령)")
    weight_class_code = Column("c145", String, comment="Code for Weight Class (체급 코드)")
    aid_text = Column("c146", String, comment="Aid Text (도움 텍스트)")
    wing_info = Column("c147", String, comment="Wing information of the aircraft involved in the investigation. (조사에 참여한 항공기의 날개 정보.)")
    wing_info_text = Column("c148", String, comment="Wing information of the aircraft text (항공기 텍스트의 날개 정보)")
    power_type = Column("c149", String, comment="Powered, Nonpowered, Optional (전원 공급, 비전원 공급, 선택 사항)")
    c150_text = Column("c150", String, comment="Text for element C150 (요소 C150의 텍스트)")
    engine_count = Column("c151", String, comment="Number of engines on aircraft (항공기 엔진 수)")
    engine_design_code = Column("c152", String, comment="Code representing typical engine design characteristics of a specific aircraft model. (특정 항공기 모델의 일반적인 엔진 설계 특성을 나타내는 코드.)")
    power_class = Column("c153", String, comment="Under or over 750 hp. (750마력 이하 또는 그 이상.)")
    c153_text = Column("c154", String, comment="Text for element C153. (C153 요소의 텍스트.)")
    engine_type_code = Column("c155", String, comment="Type of the engine code. (엔진 코드의 유형.)")
    engine_type_desc = Column("c156", String, comment="Type of engine. (엔진 유형.)")
    landing_gear_code = Column("c157", String, comment="Type of Landing Gear code. (랜딩 기어 코드의 유형.)")
    landing_gear_desc = Column("c158", String, comment="Type of landing gear. (랜딩 기어의 종류.)")
    additional_cause_code = Column("c160", String, comment="Additional cause factor code (추가 원인 요인 코드)")
    additional_cause_text = Column("c161", String, comment="Additional cause factor text (추가 원인 요인 텍스트)")
    additional_cause2_code = Column("c162", String, comment="2nd Additional cause factor code (2차 추가 원인 요인 코드)")
    additional_cause2_text = Column("c163", String, comment="2nd Additional cause factor text (2차 추가 원인 요인 텍스트)")
    support_factor_ops_text = Column("c183", String, comment="Supporting Factor Text OPERATIONAL (지원 요소 텍스트 운영)")
    support_factor_ops_code_a = Column("c184", String, comment="Supporting cause factor A code. OPERATIONAL (지원 원인 요인 A 코드. 작동 중)")
    support_factor_ops_text_b = Column("c191", String, comment="Supporting cause factor B text. OPERATIONAL (원인 요인 B 텍스트 지원. 운영 중)")
    support_factor_ops_code_b = Column("c192", String, comment="Supporting cause factor B code. OPERATIONAL (지원 원인 요인 B 코드. 운영 중)")
    system_gen_field = Column("c203", String, comment="This field is generated by the system so no edits are performed. (이 필드는 시스템에서 생성되므로 편집이 수행되지 않습니다.)")
    case_seq_number = Column("c204", String, comment="Sequential number assigned to cases dealt with in the current year. (해당 연도에 처리된 사건에 할당된 일련 번호.)")
    entry_date = Column("c205", String, comment="Date that the case information is originally entered. (사례 정보가 처음 입력된 날짜.)")
    form_019_date = Column("c206", String, comment="Date the 0.19 form was received by the office. (사무실에서 0.19 양식을 받은 날짜.)")
    form_04_date = Column("c207", String, comment="Date the 0.4 form was received by the office. (사무실에서 0.4 양식을 받은 날짜.)")
    supplement_data_date = Column("c208", String, comment="Date that any supplemental data was received by the office. (사무실에서 추가 데이터를 받은 날짜.)")
    last_modified = Column("c210", String, comment="Date that the document was last modified. (문서가 마지막으로 수정된 날짜.)")
    operator_group = Column("c214", String, comment="Group of the air operator involved in the investigation. (조사에 참여한 항공 운영자 그룹.)")
    pic_dob = Column("c229", String, comment="Date of Birth of PIC (PIC 출생일)")
    second_pilot_dob = Column("c230", String, comment="Date of birth of second Pilot (두 번째 조종사의 출생일)")
    pic_fatal_flag = Column("c233", String, comment="Flag to indicate if the pilot was killed. (조종사가 사망했는지 여부를 나타내는 깃발.)")
    second_pilot_fatal_flag = Column("c234", String, comment="Flag to indicate if the second pilot was killed. (두 번째 조종사가 사망했는지 여부를 나타내는 깃발.)")
    wind_dir = Column("c240", String, comment="Wind direction (풍향)")
    wind_speed = Column("c241", String, comment="Wind speed in miles per hours (풍속(시속 마일))")
    gust_flag = Column("c242", String, comment="Gust indicator flag (돌풍 지시기)")
    gust_speed = Column("c243", String, comment="Gust speed in miles per hour (돌풍 속도(시속 마일))")
    flight_plan_code = Column("c244", String, comment="Flight plan code (비행 계획 코드)")
    all_injuries_count = Column("c250", String, comment="All injuries including crew passengers and public. (승무원 승객과 일반인을 포함한 모든 부상.)")
    rebuttal_statement = Column("c790", String, comment="Consolidated Statement Rebuttal (통합 진술 반박)")

    narratives = relationship("AccidentNarrative", back_populates="meta")

class AccidentNarrative(Base):
    __tablename__ = "E_FILE"

    report_id = Column("c5", String, ForeignKey("A_FILE.c5"), primary_key=True)
    description = Column("remark", Text)

    meta = relationship("AccidentMeta", back_populates="narratives")

class AnalysisResult(Base):
    __tablename__ = "analysis_results"

    id = Column(Integer, primary_key=True, index=True)
    query = Column(Text, comment="Item Definition / Query")
    mode = Column(String(50), comment="rag or base")
    result_text = Column(Text, comment="Full LLM Output")
    parsed_data = Column(Text, comment="JSON string of logical rows extracted from table")
    metrics = Column(Text, comment="JSON string of evaluation metrics")
    ground_truth = Column(Text, nullable=True, comment="Ground Truth for evaluation")
    is_saved = Column(Integer, default=0, comment="Boolean flag: 1 if user saved explicitly, 0 otherwise")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class ManualEvaluation(Base):
    __tablename__ = "manual_evaluations"

    id = Column(Integer, primary_key=True, index=True)
    analysis_id = Column(Integer, ForeignKey("analysis_results.id"))
    evaluator = Column(String(100), nullable=True)
    score = Column(Integer)
    checklist_data = Column(Text, comment="JSON string of checklist state")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    analysis_result = relationship("AnalysisResult")
